on: pull_request
name: Check PR
jobs:
  check_pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'
    - name: checkout code
      uses: actions/checkout@v2
    - name: fetch deps
      run: go get
    - name: install checkers
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install golang.org/x/lint/golint@latest
        go install github.com/client9/misspell/cmd/misspell@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest
    - name: check
      run: make check
    - name: Build Image
      uses: docker/build-push-action@v1
      with:
        push: false
